Separate Readme sections for Source mode, Reflect mode and Flags
golang/mock pull request #495
Opened 2020-10-23 10:36 UTC by dstivanov

**Description**

As a newbie in the tooling I was not able to find out that there are two modes of generation (Source and Reflect) from first glance. I believe that this small change can help the other like me.

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes tests - N/A

**Reviewer Notes**

- [ ] The code flow looks good.
- [ ] Tests added.

**Release Notes**

N/A - no release changes, only markdown changes

2020-10-23 10:37 UTC, dstivanov commented
@googlebot I signed it

2020-10-23 14:10 UTC, codyoss requested changes

2020-10-23 14:10 UTC, codyoss commented on README.md
> +#### Source mode
```suggestion

#### Source mode
```

2020-10-23 14:10 UTC, codyoss commented on README.md
> +#### Flags
```suggestion

#### Flags
```

2020-10-23 14:10 UTC, codyoss commented
Thanks for the PR, just a couple small nits.

2020-10-26 14:28 UTC, codyoss approved these changes

2020-10-26 14:28 UTC, merged