parse arrays with const length correctly (#294)
golang/mock pull request #520
Opened 2021-02-14 03:08 UTC by fsmiamoto

Fixes #294 

**Description**
As described in the related issue - #294 - parsing an array with a const defined size would generate a panic.

This PR attempts fix that issue.

Would love to hear some feedback :slightly_smiling_face: 

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes tests

**Reviewer Notes**

- [ ] The code flow looks good.
- [ ] Tests added.

2021-02-23 21:52 UTC, codyoss requested changes
Just a couple of small things, thanks for the contribution!

2021-02-23 21:52 UTC, codyoss commented on mockgen/internal/tests/const_array_length/input.go
> +//go:generate mockgen -package const_length -destination mock.go -source input.go
nit: could you move this line below the package declaration. Having it here will have it show up in godoc. 

I know it is done this way in other packages, but I would like to refactor these sometime.

2021-02-23 21:52 UTC, codyoss commented on mockgen/internal/tests/const_array_length/input.go
> +	F() [C]int
Would you add another function to test the other case for arrays: `Bar() [2]int`

2021-02-23 21:52 UTC, codyoss commented on mockgen/parse_test.go
> +		t.Fatalf("Expected return type %v but got %v", expect, got)
nit: Could you reverse this message so it is in the form of "got %v, want %v". Again I know this is not consistent with some of the other tests, but they should be refactored. See [useful test failures](https://gist.github.com/adamveld12/c0d9f0d5f0e1fba1e551#useful-test-failures).

2021-02-23 23:04 UTC, fsmiamoto commented
Thanks for the review! I guess we should be good now.

2021-02-24 22:31 UTC, codyoss approved these changes

2021-02-24 22:31 UTC, merged

2021-02-24 22:32 UTC, codyoss commented
Thank you for your contribution! 🎆