Add argMatcher for creating new calls
golang/mock pull request #581
Opened 2021-07-27 11:44 UTC by tsamsiyu

Suggested change provides opportunity to override default matcher in which arguments are wrapped when creating a new call.

Currently "gomock.Eq" is hardcoded for these purposes, and if you need to change it and you already have hundreds of tests, it seems merely possible.

2021-07-27 11:57 UTC, tsamsiyu commented
@googlebot I signed it!

2021-07-27 11:58 UTC, tsamsiyu commented
@googlebot I fixed it.

2021-07-27 11:59 UTC, tsamsiyu commented
@googlebot I fixed it.

2021-07-27 12:03 UTC, tsamsiyu commented
@googlebot I fixed it.

2021-09-17 15:03 UTC, codyoss requested changes
Sorry for the delay of reviewing this. Can you please open up an issue for discussion about adding such a feature. Thanks.

2021-10-01 17:07 UTC, codyoss commented
Closing this for now. Feel free to reopen after we have had a chance to discuss the changes in an issue first.

2021-10-01 17:07 UTC, closed without merging