feat: new in slice matcher
golang/mock pull request #582
Opened 2021-08-24 14:45 UTC by MakDon

This PR provides a new matcher that returns true if the given value `Eq` one of the `want` elements.

```Golang
// Example usage:
m := In([]int{1,2})
m.Matches(1) // returns true
m.Matches(2) // returns true
m.Matches(3) // returns false
```

2021-09-17 15:01 UTC, codyoss commented
@MakDon Can you please open up an issue for discussion about adding such a feature. Thanks.

2021-09-17 15:02 UTC, codyoss requested changes
See comment above.

2021-09-17 15:22 UTC, MakDon commented
@codyoss Hi codyoss, thanks for your review. 

I've opened up an issue #590 for further discussion.

2021-10-01 17:23 UTC, codyoss commented
Closing this for now until discussion on the issue has settled.  I will reopen if we decide to move forward with these changes.

2021-10-01 17:23 UTC, closed without merging