feat: allow setting args for variadic functions
golang/mock pull request #595
Opened 2021-10-15 22:50 UTC by bergotorino

The gomock's Call interface allows for setting a value to a specified
argument, making it convinient to work with functions that return data
through pointer arguments. However, this is not possible for variadic
functions, the error is:

  SetArg(1, ...) called for a method with 1 args...

The root cause is that the variadic argument in a form of
...interface{} is threated as single value instead of being treated as
slice.

This commit changes this situation by making sure that the variadic
arguments that are a slice are treated as slices. As a consequence it is
now possible to set argument value for variadic functions.

See: https://github.com/golang/mock/issues/174

2021-12-30 19:19 UTC, codyoss commented on gomock/call.go
> +	if (n < 0 || n >= mt.NumIn()) && !mt.IsVariadic() {
Could you please add some tests for this. You can either do a traditional tests or a sample code generation like others in the `mockgen/internal/test` dir.

2021-12-30 19:19 UTC, codyoss requested changes
Please add tests :)

2022-04-11 16:35 UTC, bergotorino commented
Sure, will do. Thanks for review and sorry for missing your comments on time

2022-05-11 11:17 UTC, mvrahden commented
@bergotorino are you still planning to do this?

2022-07-08 16:50 UTC, codyoss commented
Closing due to lack of response.

2022-07-08 16:50 UTC, closed without merging